export const municipalities = {
  "001": { municipality: "Managua", department: "Managua" },
  "002": { municipality: "San Rafael del Sur", department: "Managua" },
  "003": { municipality: "Tipitapa", department: "Managua" },
  "004": { municipality: "Villa Carlos Fonseca", department: "Managua" },
  "005": { municipality: "San Francisco Libre", department: "Managua" },
  "006": { municipality: "Mateare", department: "Managua" },
  "007": { municipality: "Ticuantepe", department: "Managua" },
  "008": { municipality: "Ciudad Sandino", department: "Managua" },
  "009": { municipality: "El Crucero", department: "Managua" },

  "041": { municipality: "Jinotepe", department: "Carazo" },
  "042": { municipality: "Diriamba", department: "Carazo" },
  "043": { municipality: "San Marcos", department: "Carazo" },
  "044": { municipality: "Santa Teresa", department: "Carazo" },
  "045": { municipality: "Dolores", department: "Carazo" },
  "046": { municipality: "La Paz Carazo", department: "Carazo" },
  "047": { municipality: "El Rosario", department: "Carazo" },
  "048": { municipality: "La Conquista", department: "Carazo" },

  "081": { municipality: "Chinandega", department: "Chinandega" },
  "082": { municipality: "Corinto", department: "Chinandega" },
  "083": { municipality: "El Realejo", department: "Chinandega" },
  "084": { municipality: "Chichigalpa", department: "Chinandega" },
  "085": { municipality: "Posoltega", department: "Chinandega" },
  "086": { municipality: "El Viejo", department: "Chinandega" },
  "087": { municipality: "Puerto Morazán", department: "Chinandega" },
  "088": { municipality: "Somotillo", department: "Chinandega" },
  "089": { municipality: "Villa Nueva", department: "Chinandega" },
  "090": { municipality: "Santo Tomás del Norte", department: "Chinandega" },
  "091": { municipality: "Cinco Pinos", department: "Chinandega" },
  "092": { municipality: "San Francisco del Norte", department: "Chinandega" },
  "093": { municipality: "San Pedro del Norte", department: "Chinandega" },

  "121": { municipality: "Juigalpa", department: "Chontales" },
  "122": { municipality: "Acoyapa", department: "Chontales" },
  "123": { municipality: "Santo Tomás", department: "Chontales" },
  "124": { municipality: "Villa Sandino", department: "Chontales" },
  "125": { municipality: "San Pedro de Lóvago", department: "Chontales" },
  "126": { municipality: "La Libertad", department: "Chontales" },
  "127": { municipality: "Santo Domingo", department: "Chontales" },
  "128": { municipality: "Comalapa", department: "Chontales" },
  "129": { municipality: "San Francisco Cuapa", department: "Chontales" },
  "130": { municipality: "El Coral", department: "Chontales" },

  "161": { municipality: "Estelí", department: "Estelí" },
  "162": { municipality: "Pueblo Nuevo", department: "Estelí" },
  "163": { municipality: "Condega", department: "Estelí" },
  "164": { municipality: "San Juan Limay", department: "Estelí" },
  "165": { municipality: "La Trinidad", department: "Estelí" },
  "166": { municipality: "San Nicolás", department: "Estelí" },

  "201": { municipality: "Granada", department: "Granada" },
  "202": { municipality: "Nandaime", department: "Granada" },
  "203": { municipality: "Diriomo", department: "Granada" },
  "204": { municipality: "Diriá", department: "Granada" },

  "241": { municipality: "Jinotega", department: "Jinotega" },
  "242": { municipality: "San Rafael del Norte", department: "Jinotega" },
  "243": { municipality: "San Sebastián Yalí", department: "Jinotega" },
  "244": { municipality: "La Concordia", department: "Jinotega" },
  "245": { municipality: "San José de Bocay", department: "Jinotega" },
  "246": { municipality: "El Cuá Bocay", department: "Jinotega" },
  "247": { municipality: "Santa María Pantasma", department: "Jinotega" },

  "281": { municipality: "León", department: "León" },
  "283": { municipality: "El Jicaral", department: "León" },
  "284": { municipality: "La Paz Centro", department: "León" },
  "285": { municipality: "Santa Rosa del Peñón", department: "León" },
  "286": { municipality: "Quetzalguaque", department: "León" },
  "287": { municipality: "Nagarote", department: "León" },
  "288": { municipality: "El Sauce", department: "León" },
  "289": { municipality: "Achuapa", department: "León" },
  "290": { municipality: "Telica", department: "León" },
  "291": { municipality: "Larreynaga Malpaisillo", department: "León" },

  "321": { municipality: "Somoto", department: "Madriz" },
  "322": { municipality: "Telpaneca", department: "Madriz" },
  "323": { municipality: "San Juan Río Coco", department: "Madriz" },
  "324": { municipality: "Palacagüina", department: "Madriz" },
  "325": { municipality: "Yalagüina", department: "Madriz" },
  "326": { municipality: "Totogalpa", department: "Madriz" },
  "327": { municipality: "San Lucas", department: "Madriz" },
  "328": { municipality: "La Sabanas", department: "Madriz" },
  "329": { municipality: "San José de Cusmapa", department: "Madriz" },

  "361": { municipality: "Boaco", department: "Boaco" },
  "362": { municipality: "Camoapa", department: "Boaco" },
  "363": { municipality: "Santa Lucía", department: "Boaco" },
  "364": { municipality: "San José del Remate", department: "Boaco" },
  "365": { municipality: "San Lorenzo", department: "Boaco" },
  "366": { municipality: "Teustepe", department: "Boaco" },

  "401": { municipality: "Masaya", department: "Masaya" },
  "402": { municipality: "Nindirí", department: "Masaya" },
  "403": { municipality: "Tisma", department: "Masaya" },
  "404": { municipality: "Catarina", department: "Masaya" },
  "405": { municipality: "San Juan Oriente", department: "Masaya" },
  "406": { municipality: "Niquinohomo", department: "Masaya" },
  "407": { municipality: "Nandasmo", department: "Masaya" },
  "408": { municipality: "Masatepe", department: "Masaya" },
  "409": { municipality: "La Concepción", department: "Masaya" },

  "441": { municipality: "Matagalpa", department: "Matagalpa" },
  "442": { municipality: "San Ramón", department: "Matagalpa" },
  "443": { municipality: "Matiguás", department: "Matagalpa" },
  "444": { municipality: "Muy Muy", department: "Matagalpa" },
  "445": { municipality: "Esquipulas", department: "Matagalpa" },
  "446": { municipality: "San Dionisio", department: "Matagalpa" },
  "447": { municipality: "San Isidro", department: "Matagalpa" },
  "448": { municipality: "SéBaco", department: "Matagalpa" },
  "449": { municipality: "Ciudad Darío", department: "Matagalpa" },
  "450": { municipality: "Terrabona", department: "Matagalpa" },
  "451": { municipality: "Río Blanco", department: "Matagalpa" },
  "452": { municipality: "Tuma La Dalia", department: "Matagalpa" },
  "453": { municipality: "Rancho Grande", department: "Matagalpa" },

  "481": { municipality: "Ocotal", department: "Nueva Segovia" },
  "482": { municipality: "Santa María", department: "Nueva Segovia" },
  "483": { municipality: "Macuelizo", department: "Nueva Segovia" },
  "484": { municipality: "Dipilto", department: "Nueva Segovia" },
  "485": { municipality: "Ciudad Antigua", department: "Nueva Segovia" },
  "486": { municipality: "Mozonte", department: "Nueva Segovia" },
  "487": { municipality: "San Fernando", department: "Nueva Segovia" },
  "488": { municipality: "El Jícaro", department: "Nueva Segovia" },
  "489": { municipality: "Jalapa", department: "Nueva Segovia" },
  "490": { municipality: "Murra", department: "Nueva Segovia" },
  "491": { municipality: "Quilalí", department: "Nueva Segovia" },
  "492": { municipality: "Wiwilí", department: "Nueva Segovia" },
  "493": { municipality: "Wiwilí Nueva Segovia", department: "Nueva Segovia" },

  "521": { municipality: "San Carlos", department: "Río San Juan" },
  "522": { municipality: "El Castillo", department: "Río San Juan" },
  "523": { municipality: "San Miguelito", department: "Río San Juan" },
  "524": { municipality: "Morrito", department: "Río San Juan" },
  "525": { municipality: "San Juan del Norte", department: "Río San Juan" },
  "526": { municipality: "El Almendro", department: "Río San Juan" },

  "561": { municipality: "Rivas", department: "Rivas" },
  "562": { municipality: "San Jorge", department: "Rivas" },
  "563": { municipality: "Buenos Aires", department: "Rivas" },
  "564": { municipality: "Potosí", department: "Rivas" },
  "565": { municipality: "Belén", department: "Rivas" },
  "566": { municipality: "Tola", department: "Rivas" },
  "567": { municipality: "San Juan Sur", department: "Rivas" },
  "568": { municipality: "Cárdenas", department: "Rivas" },
  "569": { municipality: "Moyogalpa", department: "Rivas" },
  "570": { municipality: "Altagracia", department: "Rivas" },

  // Regiones Autónomas / Atlántico Norte y Sur
  "607": { municipality: "Puerto Cabezas (Bilwi)", department: "Atlántico Norte" },
  "608": { municipality: "Waspán", department: "Atlántico Norte" },
  "610": { municipality: "Siuna", department: "Atlántico Norte" },
  "611": { municipality: "Bonanza", department: "Atlántico Norte" },
  "612": { municipality: "Rosita", department: "Atlántico Norte" },
  "615": { municipality: "Bocana Paiwás", department: "Atlántico Norte" },
  "454": { municipality: "Waslala", department: "Atlántico Norte" },
  "602": { municipality: "Corn Island", department: "Atlántico Norte" },

  "601": { municipality: "Bluefields", department: "Atlántico Sur" },
  "603": { municipality: "El Rama", department: "Atlántico Sur" },
  "604": { municipality: "Muelle de los Bueyes", department: "Atlántico Sur" },
  "605": { municipality: "La Cruz de Río Grande", department: "Atlántico Sur" },
  "606": { municipality: "Prinzapolka", department: "Atlántico Sur" },
  "616": { municipality: "Nueva Guinea", department: "Atlántico Sur" },
  "619": { municipality: "Tortuguero", department: "Atlántico Sur" },
  "624": { municipality: "Kukra Hill", department: "Atlántico Sur" },
  "626": { municipality: "Laguna de Perlas", department: "Atlántico Sur" },
  "627": { municipality: "Desembocadura Río Grande", department: "Atlántico Sur" },
  "628": { municipality: "El Ayote", department: "Atlántico Sur" }
};